// This file is generated by Slice Machine. Update with care!

import Prodotto from './Prodotto';
import Product from './Product';

export {
	Prodotto,
	Product,
};

export const components = {
	prodotto: Prodotto,
	product: Product,
};
