import Head from "next/head";
import SectionAvatar from "../components/sectionAvatar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        ></meta>
      </Head>

      <div className="section" data-scroll-section data-scroll-position>
        <div className="video-wrapper">
          <video
            id="video-hero-id"
            className="video-hero"
            autoPlay
            loop
            muted={true}
            playsInline
          >
            <source src={"/video/video1.mp4"} />
          </video>
        </div>
      </div>

      <div className="section-avatar" data-scroll-section>
        <SectionAvatar image={"/public/avatar.jpg"} />
      </div>
      <div className="section-footer" data-scroll-section>
        <p className="section-footer-text"  data-scroll>
          Aute cillum excepteur excepteur magna enim deserunt velit aute commodo adipisicing.
        </p>
      </div>
    </>
  );
}
